### ISSUE TITLE
Onion ID length 

### ISSUE THREAD

**Issue by aayushsinha44** [ipsn/go-libtor#18]
Is it possible to change the length of onion ID that we get, i.e. can ask for greater sized onion ID that we get from the following code?

`onion, err := t.Listen(listenCtx, &tor.ListenConf{Version3: true, RemotePorts: []int{80}})`

**Comment by karalabe** [comment]
Isn't the onion ID simply a public key? That's defined by the cryptography used by Tor, it's not something that can be configured.
