### ISSUE TITLE
The filename or extension is too long.

### ISSUE THREAD

**Issue by tgbv** [ipsn/go-libtor#28]
I'm receiving the following error amid including go-libtor in my project:
```
go build github.com/ipsn/go-libtor/libtor: C:\Program Files\Go\pkg\tool\windows_amd64\cgo.exe: fork/exec C:\Program Files\Go\pkg\tool\windows_amd64\cgo.exe: The filename or extension is too long.
```

How should I fix it?

**Comment by tgbv** [comment]
Related to https://github.com/golang/go/issues/18468

Switched to ubuntu and error is gone.

**Comment by nochiel** [comment]
Reported upstream. https://github.com/golang/go/issues/47235
