### ISSUE TITLE
Bine's process.Process interface has new method

### ISSUE THREAD

**Issue by cretz** [ipsn/go-libtor#4]
Heads up, I added a new method `EmbeddedControlConn` to [process.Process](https://godoc.org/github.com/cretz/bine/process#Process). This was done because now, in Tor >= 0.3.5.x, there is a feature that lets us use a native socket created by Tor instead of opening our own (ref `tor_api.h`'s `tor_main_configuration_setup_control_socket`). Note, that specific feature doesn't work on Windows due to Go's lack of [Windows support for net.FileConn](https://github.com/golang/go/issues/9503). For older versions of Tor (such as this one and the default used by Bine, 0.3.5.x), just return `nil, ErrControlConnUnsupported`.

**Comment by karalabe** [comment]
Thanks for the heads up. Will add when I fix the upstream build errors.

**Comment by karalabe** [comment]
Fixed by https://github.com/ipsn/go-libtor/commit/dfda19cf892d5dce3cd1a4cb51e8f812e54b7cd9
